eureka:
  client:
    #是否向注册中心注册
    register-with-eureka: false
    #是否向注册中心定时获取服务列表
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka,http://localhost:8002/eureka
  #服务失效时间，Eureka多长时间没收到服务的renew操作，就剔除该服务，默认90秒
  instance:
    lease-expiration-duration-in-seconds: 15
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  server:
    enable-self-preservation: false
server:
  port: 8080
spring:
  application:
    name: wicv-ms-learn-discovery